export default {
  LOADING: 'LOADING',
  GET_GENRE: 'GET_GENRE',
  GET_GENRE_ERROR: 'GET_GENRE_ERROR',
  GET_MOVIES: 'GET_MOVIES',
  GET_MOVIES_ERROR: 'GET_MOVIES_ERROR',
  GET_GENRE_MOVIES: 'GET_GENRE_MOVIES',
  GET_GENRE_MOVIES_ERROR: 'GET_GENRE_MOVIES_ERROR',
};
