export default {
  GET_MOVIE_DETAILS: 'GET_GENRE_MOVIES',
  GET_MOVIE_DETAILS_ERROR: 'GET_GENRE_MOVIES_ERROR',
  LOADING: 'LOADING',
  LOADING_RATE: 'LOADING_RATE',
  POST_RATE_MOVIE: 'POST_RATE_MOVIE',
  POST_RATE_MOVIE_ERROR: 'POST_RATE_MOVIE_ERROR',
};
